import type { LocalAiConfig } from '../config/schema.js';
import type { Confidence, DependencyImportance, DependencyRelationship } from '../indexer/types.js';
export interface SummarizeInput { targetType: 'file'|'symbol'|'dependency'|'question'; text: string; maxTokens: number; mode?: string }
export interface SummarizeOutput { summary: string; confidence: Confidence; model: string }
export interface DependencyCandidate { symbol: string; relationship: DependencyRelationship; staticSignals: string[]; summary?: string | null }
export interface RankDependenciesInput { primarySymbol: string; dependencies: DependencyCandidate[]; taskHint?: string | null }
export interface DependencyRanking { symbol: string; importance: DependencyImportance; reason: string }
export interface RankDependenciesOutput { rankings: DependencyRanking[]; model: string }
export interface LocalAiHealth { available: boolean; provider: string; model: string; reason?: string }
export interface LocalAiClient { summarize(input: SummarizeInput): Promise<SummarizeOutput>; rankDependencies(input: RankDependenciesInput): Promise<RankDependenciesOutput>; health(): Promise<LocalAiHealth> }
export function createDisabledLocalAiClient(config: LocalAiConfig): LocalAiClient { return { async summarize(){ return { summary: 'Local AI disabled; deterministic static summary used.', confidence: 'low', model: config.model }; }, async rankDependencies(input){ return { model: config.model, rankings: input.dependencies.map(d => ({ symbol: d.symbol, importance: d.staticSignals.some(s => /auth|persist|mutation|external/i.test(s)) ? 'high' : 'medium', reason: 'Static ranking because local AI is disabled.' })) }; }, async health(){ return { available: false, provider: config.provider, model: config.model, reason: 'disabled' }; } }; }
export function createLocalAiClient(config: LocalAiConfig): LocalAiClient { if (!config.enabled) return createDisabledLocalAiClient(config); return { async summarize(input){ const res = await fetch(`${config.baseUrl.replace(/\/$/, '')}/chat/completions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ model: config.model, messages: [{ role: 'user', content: `Summarize this ${input.targetType} in <= ${input.maxTokens} tokens. Do not invent paths or line numbers.\n\n${input.text}` }], temperature: 0 }) }); if (!res.ok) return { summary: 'Local AI unavailable; static fallback required.', confidence: 'low', model: config.model }; const json = await res.json() as any; return { summary: String(json.choices?.[0]?.message?.content ?? '').trim() || 'No local summary returned.', confidence: 'medium', model: config.model }; }, async rankDependencies(input){ return createDisabledLocalAiClient(config).rankDependencies(input); }, async health(){ try { const r = await fetch(config.baseUrl); return { available: r.ok, provider: config.provider, model: config.model, reason: r.ok ? undefined : `HTTP ${r.status}` }; } catch (e) { return { available: false, provider: config.provider, model: config.model, reason: e instanceof Error ? e.message : String(e) }; } } }; }
